Add files via upload
Ubn-Jr/siralamasyon_bot pull request #2
Opened 2023-04-05 02:19 UTC by haticebabaoglu

2023-04-05 02:34 UTC, haticebabaoglu commented
Error dosyasi olusturuldu, main dosyasina iplemente edilmedi.

2023-04-06 08:53 UTC, log101 requested changes
Kodlarını test etmeyi de unutma

2023-04-06 08:53 UTC, log101 commented on error.go
Hata mesajı fonksiyonu aldığı mesajı ekrana yazdırmalı

2023-04-06 08:53 UTC, log101 commented on selectionSort.go
Ya büyükten küçüğe ya küçükten büyüğe sıralasın, yada bunu nasıl yapması gerektiği bilgisini kullanıcıdan alsın

2023-04-06 08:53 UTC, log101 commented on strConvertTolist.go
lint edilmesi gerekiyor, düzensiz görünüyor vs code da bunu otomatik yapabilirsin

2023-04-25 17:46 UTC, log101 requested changes
reviewed

2023-04-25 17:51 UTC, log101 approved these changes

2023-04-25 17:52 UTC, merged